

final List<String> diseases = [
  "Severe kidney disease",
  "Liver disease",
  "Heart failure",
  "Peptic ulcer disease",
  "Asthma",
  "Diabetes",
  "Pregnancy",
  "Hypertension",
  "Chronic obstructive pulmonary disease (COPD)",
  "Glaucoma",
  "Epilepsy",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Osteoporosis",
  "Gout",
  "HIV/AIDS",
  "Tuberculosis",
  "Rheumatoid arthritis",
  "Multiple sclerosis",
  "Parkinson's disease",
  "Schizophrenia",
  "Bipolar disorder",
  "Migraine",
  "Chronic pain",
  "Insomnia",
  "Anxiety",
  "Depression",
  "Allergic rhinitis",
  "Psoriasis",
  "Eczema",
  "Chronic hepatitis",
  "Cirrhosis",
  "Diverticulitis",
  "Endometriosis",
  "Fibromyalgia",
  "Gastroesophageal reflux disease (GERD)",
  "Hemophilia",
  "Hyperlipidemia",
  "Hypokalemia",
  "Irritable bowel syndrome (IBS)",
  "Lupus",
  "Myasthenia gravis",
  "Narcolepsy",
  "Obesity",
  "Osteoarthritis",
  "Pancreatitis",
  "Polycystic ovary syndrome (PCOS)",
  "Prostate cancer",
  "Psoriatic arthritis",
  "Restless legs syndrome",
  "Rheumatic fever",
  "Sarcoidosis",
  "Sickle cell anemia",
  "Sjogren's syndrome",
  "Systemic sclerosis",
  "Ulcerative colitis",
  "Vasculitis",
];
List<String> drugs = [
  "Warfarin",
  "Metformin",
  "Lisinopril",
  "Simvastatin",
  "Paracetamol",
  "Digoxin",
  "Fluoxetine",
  "Amlodipine",
  "Prednisone",
  "Ciprofloxacin",
  "Lithium",
  "Alprazolam",
  "Ibuprofen",
  "Aspirin",
  "Omeprazole",
  "Clopidogrel",
  "Atorvastatin",
  "Diazepam",
  "Methotrexate",
  "Phenytoin",
  "Theophylline",
  "Codeine",
  "Sertraline",
  "Venlafaxine",
  "Tramadol",
  "Metoprolol",
  "Furosemide",
  "Hydrochlorothiazide",
  "Spironolactone",
  "Cimetidine",
  "Carbamazepine",
  "Erythromycin",
  "Ketoconazole",
  "Rifampin",
  "Amoxicillin",
  "Azithromycin",
  "Doxycycline",
  "Gabapentin",
  "Levothyroxine",
  "Losartan",
  "Pantoprazole",
  "Ranitidine",
  "Rosuvastatin",
  "Zolpidem",
  "Amiodarone",
  "Atenolol",
  "Baclofen",
  "Celecoxib",
  "Clonidine",
  "Cyclobenzaprine",
  "Diltiazem",
  "Duloxetine",
  "Escitalopram",
  "Esomeprazole",
  "Famotidine",
  "Fluconazole",
  "Folicacid",
  "Glimepiride",
  "Hydroxyzine",
  "Insulin",
  "Isosorbide",
  "Lamotrigine",
  "Levofloxacin",
  "Loratadine",
  "Meloxicam",
  "Montelukast",
  "Nifedipine",
  "Olanzapine",
  "Pregabalin",
  "Quetiapine",
  "Ranolazine",
  "Sildenafil",
  "Tamsulosin",
  "Topiramate",
  "Valproate"
];
